version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3

    steps:
      - checkout

      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}
          - node_modules-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package.json" }}
        
      - run: npm test
